---
title: "Analyzing the Impact of Internet User Characteristics on Ad Clicks"
author: "Xiwen Ran"
date: "Dec 22, 2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
Code and data supporting this report is available at:

## Model
## Model Specifics

```{r, results = 'hide', message = FALSE, warning =FALSE}
library(tidyverse)
library(tinytex)
ad_data = read.csv('~/Desktop/STA304/advertising.csv')
ad_data_subset = ad_data[,c(1,3,4,10)]
write.csv(ad_data_subset, file="advertising_cleaning.csv")
head(ad_data_subset)
summary(ad_data_subset)

## Standard Logistic Regression
mylogit<-glm(Clicked.on.Ad ~ Daily.Internet.Usage + Daily.Time.Spent.on.Site +
              Area.Income, data=ad_data_subset, family="binomial")
summary(mylogit)

## log(p/(1-p)) = (2.866e+01) + (-6.185e-02)*Daily.Internet.Usage + 
##                (-1.676e-01)*Daily.Time.Spent.on.Site + 
##                (-1.032e-04)*Area.Income

```

## Results
## Figure 1

```{r, results = 'hide', message = FALSE, warning =FALSE}
library(ggplot2)
ad_data_subset$Clicked.on.Ad <- recode_factor(ad_data_subset$Clicked.on.Ad, 
                                              '0' = 'Did Not Click', 
                                              '1' = 'Clicked')
ggplot(ad_data_subset, aes(x = Daily.Internet.Usage, fill = Clicked.on.Ad)) +
  geom_histogram(position = "identity", alpha = 0.5) + 
  labs(x="Daily Internet Usage (Minutes)", y = "Count")

```

## Figure 2

```{r, results = 'hide', message = FALSE, warning =FALSE}
ad_data_subset$Clicked.on.Ad <- recode_factor(ad_data_subset$Clicked.on.Ad, 
                                              '0' = 'Did Not Click', 
                                              '1' = 'Clicked')
ggplot(ad_data_subset, aes(x = Daily.Time.Spent.on.Site, fill = Clicked.on.Ad)) + geom_histogram(position = "identity", alpha = 0.5) + labs(x="Daily Time Spent on Site (Minutes)", y = "Count")

```

## Figure 3

```{r, results = 'hide', message = FALSE, warning =FALSE}
ad_data_subset$Clicked.on.Ad <- recode_factor(ad_data_subset$Clicked.on.Ad, 
                                              '0' = 'Did Not Click', 
                                              '1' = 'Clicked')
ggplot(ad_data_subset, aes(x = Area.Income, fill = Clicked.on.Ad)) + geom_histogram(position = "identity", alpha = 0.5) + labs(x="Area.Income ($)", y = "Count")

```
